<a href="https://colab.research.google.com/github/victorvidigalxz/1CCA-Pyton-FIAP-2026/blob/main/C%C3%B3pia_de_Aula_04_analise_de_Dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exemplo - Analise de daos de consmidores de energia eletrica

In [ ]:
# Importando biblioteca para manipulacao de tabelas
import pandas as pd

In [ ]:
tabela = pd.read_csv ("/content/basededados.csv")

In [ ]:
tabela.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [ ]:
# Vizualizando primeiros registros
# Linhas ------> registros
# Colunas -----> atributos ------> features
tabela.head(15)

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-01-12 00:00:00,2026-03-31 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-03-31 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-03-06 00:00:00,2026-03-31 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-09-05 00:00:00,2026-03-31 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-03-31 02:57:00,1.372,0.054,243.95,5.6,0,0,18
5,2007-06-22 00:00:00,2026-03-31 16:36:00,0.284,0.254,241.54,1.6,0,1,0
6,2009-11-08 00:00:00,2026-03-31 17:48:00,0.196,0.068,244.52,0.8,0,0,1
7,2008-10-05 00:00:00,2026-03-31 18:46:00,2.234,0.270,239.05,9.4,0,0,29
8,2009-08-12 00:00:00,2026-03-31 15:25:00,0.486,0.120,249.24,2.0,0,2,0
9,2010-04-01 00:00:00,2026-03-31 22:31:00,1.842,0.120,245.22,7.4,0,0,19
10,2010-06-22 00:00:00,2026-03-31 21:20:00,0.752,0.102,242.20,3.2,1,0,1
11,2010-10-25 00:00:00,2026-03-31 07:51:00,2.192,0.000,238.17,9.2,0,0,18
12,2009-11-17 00:00:00,2026-03-31 11:55:00,1.308,0.000,242.32,5.4,0,0,19
13,2008-05-05 00:00:00,2026-03-31 15:37:00,0.424,0.226,242.65,2.0,0,0,1
14,2008-02-18 00:00:00,2026-03-31 09:04:00,1.288,0.000,239.65,5.2,0,0,17

In [ ]:
tabela.columns

Index(['Date', 'Time', 'Global_active_power', 'Global_reactive_power',
       'Voltage', 'Global_intensity', 'Sub_metering_1', 'Sub_metering_2',
       'Sub_metering_3'],
      dtype='object')

In [ ]:
# Estatisticas descritivas das colunas ---->
# Exemplo: Voltage (Tensao, em Volts) e Global_intensity (Correntes, em Aperes)

# Media aritimetica ------> mean
media_tensao = tabela ["Voltage"].mean()
print(f"A Media da tensao sera de: {media_tensao:.2f}V")
# Mediana -------> median
mediana_tensao = tabela ["Voltage"].median()
print(f"A Mediana da tensao sera de: {mediana_tensao:.2f}V")
#Desvio Padrao --------> standart Deviatin std
desvio_padrao = tabela ["Voltage"].std()
print(f"O desvio padrao sera de: {desvio_padrao:.2f}V")

A Media da tensao sera de: 240.83V
A Mediana da tensao sera de: 241.00V
O desvio padrao sera de: 3.25V

In [ ]:
# Estatisticas descritivas das colunas ---->
# Exemplo: Voltage (Tensao, em Volts) e Global_intensity (Correntes, em Aperes)

# Media aritimetica ------> mean
media_tensao = tabela ["Global_intensity"].mean()
print(f"A Media da tensao sera de: {media_tensao:.2f}A")
# Mediana -------> median
mediana_tensao = tabela ["Global_intensity"].median()
print(f"A Mediana da tensao sera de: {mediana_tensao:.2f}A")
#Desvio Padrao --------> standart Deviatin std
desvio_padrao = tabela ["Global_intensity"].std()
print(f"O desvio padrao sera de: {desvio_padrao:.2f}A")

A Media da tensao sera de: 4.63A
A Mediana da tensao sera de: 2.60A
O desvio padrao sera de: 4.47A

In [ ]:
tabela.head()

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3
0,2008-01-12 00:00:00,2026-03-31 09:44:00,1.502,0.074,240.17,6.4,0,0,18
1,2006-12-17 00:00:00,2026-03-31 23:39:00,0.374,0.264,245.50,1.8,0,2,0
2,2009-03-06 00:00:00,2026-03-31 17:01:00,0.620,0.300,239.85,3.0,0,1,1
3,2007-09-05 00:00:00,2026-03-31 05:53:00,0.280,0.200,235.72,1.4,0,0,0
4,2008-12-14 00:00:00,2026-03-31 02:57:00,1.372,0.054,243.95,5.6,0,0,18

In [ ]:
# adicionandpo uma coluna com Potencia Aparente Calculada
# Potencia Aparente = Tendao x Corrente
tabela ["Pot_Calc_1"] = tabela ["Voltage"] * tabela ["Global_intensity"]
tabela.head()


# Pot_Calc_2 = (Global_active_power**2 + global_reactive_power**2)**0.5

,Date,Time,Global_active_power,Global_reactive_power,Voltage,Global_intensity,Sub_metering_1,Sub_metering_2,Sub_metering_3,Pot_Calc_1
0,2008-01-12 00:00:00,2026-03-31 09:44:00,1.502,0.074,240.17,6.4,0,0,18,1537.088
1,2006-12-17 00:00:00,2026-03-31 23:39:00,0.374,0.264,245.50,1.8,0,2,0,441.900
2,2009-03-06 00:00:00,2026-03-31 17:01:00,0.620,0.300,239.85,3.0,0,1,1,719.550
3,2007-09-05 00:00:00,2026-03-31 05:53:00,0.280,0.200,235.72,1.4,0,0,0,330.008
4,2008-12-14 00:00:00,2026-03-31 02:57:00,1.372,0.054,243.95,5.6,0,0,18,1366.120